// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLvZH7sfwnoCC68Jz1MduPt_JT8LkFQdw',
    appId: '1:450145576246:web:37d68160a087746f483f97',
    messagingSenderId: '450145576246',
    projectId: 'threads-hen-bc053',
    authDomain: 'threads-hen-bc053.firebaseapp.com',
    storageBucket: 'threads-hen-bc053.appspot.com',
    measurementId: 'G-BJGC140GP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgQ84nKgZMaFlxRaLK0K_iiFijlToHfB0',
    appId: '1:450145576246:android:eb734cdd8f2944ce483f97',
    messagingSenderId: '450145576246',
    projectId: 'threads-hen-bc053',
    storageBucket: 'threads-hen-bc053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQdL1sIKFWZGW7LaLSvcrAJFJu94VXSTI',
    appId: '1:450145576246:ios:e7bc5a89bce90a66483f97',
    messagingSenderId: '450145576246',
    projectId: 'threads-hen-bc053',
    storageBucket: 'threads-hen-bc053.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQdL1sIKFWZGW7LaLSvcrAJFJu94VXSTI',
    appId: '1:450145576246:ios:e7bc5a89bce90a66483f97',
    messagingSenderId: '450145576246',
    projectId: 'threads-hen-bc053',
    storageBucket: 'threads-hen-bc053.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLvZH7sfwnoCC68Jz1MduPt_JT8LkFQdw',
    appId: '1:450145576246:web:da6cab497bdfe323483f97',
    messagingSenderId: '450145576246',
    projectId: 'threads-hen-bc053',
    authDomain: 'threads-hen-bc053.firebaseapp.com',
    storageBucket: 'threads-hen-bc053.appspot.com',
    measurementId: 'G-6NZBCQPQ2W',
  );
}
